version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nexo_db_prod
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - nexo_network_prod

  backend:
    build: ./backend
    container_name: nexo_backend_prod
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000" # Optional: Expose if you want direct access, but Nginx handles it
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    networks:
      - nexo_network_prod

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
      args:
        - VITE_NEXO_BACKEND_URL=http://188.166.19.103
    container_name: nexo_frontend_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - nexo_network_prod

volumes:
  postgres_data_prod:

networks:
  nexo_network_prod:
    driver: bridge
